### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/targer#35]
http://ltdemos.informatik.uni-hamburg.de/argsearch 

![image](https://user-images.githubusercontent.com/1456830/47500412-0e6a2780-d863-11e8-8997-e7c12512cdb2.png)

no images

**Comment by username3020** [comment]
I'm sorry, I am not able to reproduce this behaviour on test machine. Would be helpful to see what configuration is used on ltdemos apache.
