### ISSUE TITLE
Backup deployment in Weimar

### ISSUE THREAD

**Issue by heinrichreimer** [uhh-lt/targer#47]
We should mirror TARGER, including its Elasticsearch index for deployment on Webis clusters.

**Comment by heinrichreimer** [comment]
The basic idea is to build Docker images for frontend and backend, and then deploy to the Webis Kubernetes cluster.

**Comment by heinrichreimer** [comment]
My first steps now, as we have made a copy of the index and models on the Webis file servers, should be debugging the backend Docker image. (The frontend image seems to build and run just fine at first glance.)

**Comment by heinrichreimer** [comment]
Hey @alexteua, sorry to bother you again.
I've run into problems trying to restore the Elasticsearch index.
Did you backup using the Elasticsearch [Snapshot & Restore API](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html)?
If I mount the backup to the Elasticsearch nodes, and create a snapshot repository pointing to the backup directory, Elasticsearch doesn't seem to find any snapshot.

**Comment by heinrichreimer** [comment]
BTW, argument tagging is already running in Weimar:
Frontend: http://betaweb001.medien.uni-weimar.de:30294/
Backend: http://betaweb001.medien.uni-weimar.de:30293/apidocs/
(You might need to access the server from Webis VPN.)

**Comment by alexanderpanchenko** [comment]
As far as i know Oleksiy did not backup indices using snapshots...

**Comment by heinrichreimer** [comment]
So this is an actual copy of the disk?
If so, I don't think we'll be able to use it for bootstrapping the Weimar Elasticsearch.
We're doing on Kubernetes, so the for structure won't be the same.

**Comment by alexanderpanchenko** [comment]
Did you downloaded the index on one machine in Weimar? If so and you can make it run on a single machine then it shoud be possible to create such a snapshot on your side.

**Comment by alexanderpanchenko** [comment]
But first you need to make it working on your side not in a non-distributed way but just in the same way as it currently run it in Hamburg.

**Comment by heinrichreimer** [comment]
Deployment in Weimar is complete. The demo can be accessed at https://demo.webis.de/targer/.
