### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by heinrichreimer** [uhh-lt/targer#48]
I think, the large model files are problematic for the Docker image.
First, it is really hard to build it locally for testing and development, and second, it would probably cause issues when we want to publish the images to any Docker registry in order to use them for Kubernetes deployments.

One solution might be to move the model download to the image's entrypoint, so that the image can be built and tested quickly. Maybe it would also be an option to choose a subset of the pre-trained models for development purposes.

I'd be happy to discuss other approaches to this issue!

**Comment by alexanderpanchenko** [comment]
What are the current sizes? Could you give some numbers? I see the problem, but also what can be the solution: to download the models dynamically as the container is running for the first time or something else?

**Comment by heinrichreimer** [comment]
So currently the models make up for about 6GB.
One alternative, at least for the Webis deployment would be to mount the models from Ceph storage.

**Comment by heinrichreimer** [comment]
Though, that would break compatibility with Hamburg servers. I'll check out whether it is possible to configure the mounted path somehow.

**Comment by alexanderpanchenko** [comment]
6Gb seems to be indeed a lot. I however would like to have 'one click' experience as much as possible meaning that if I have my own server / laptop with Ubuntu linux and Docker there should be some (ideally one) command which would make run the system and no custom configurations should be done manually depnding on Webis or UHH. If you manage to create such kind of bash script and if it works reliably then it's fine with me.

**Comment by heinrichreimer** [comment]
I talked with @mam10eks, and we liked the idea much, to make it a Kubernetes deployment.
With [Helm](helm.sh) in particularly we can make it configurable, and it allows us to implement start-up procedures, such as importing the Elasticsearch index, and adding pretrained models to the containers.
Then, if we serve the raw files online, like it is done currently on ltdata, it should be as easy as  running `helm install [...]`.

**Comment by mam10eks** [comment]
Hi,

I think 6GB is ok (is this already the compressed size? Or compressed models in the image?).

If you really do not want to include the models into the image, I would suggest:

- The docker container contains two startup scripts
  - One script assumes that the models are available in the local filesystem
  - One script that checks if the models are already available in the local filesystem (if not, it downloads them), and after they are available it runs the script above. This should be the default command of the image.
    - Uses md5 hash to check if the file is already downloaded
    - if md5 hash does not match (or the file does not exist) download the model from a reliable source (are the models on zenodo?)

Such a setup should be useful to deploy the same docker image in kubernetes and on local docker:

- In Kubernetes: The models are already available in ceph and mounted. Hence the pod can directly use the first script without downloading anything
- With docker only: We provide a command that mounts the download-directory where the models are expected to the host filesystem. Users can always run this command, and the models are only downloaded once (for multiple restarts).

**Comment by mam10eks** [comment]
Another solution would be to use multiple tags of the same image.
Probably I would prefer this solution.

Example what would be in the docker registry:
- targer:1.0.0 (small, without any models, assumes models are located at position x)
- targer:1.0.0-with-all-models (large image with all models)
- targer:1.0.1 (small, without any models)
- targer:1.0.2 (small, without any models)
- targer:1.1.0 (small, without any models)
- targer:1.1.0-with-all-models (large image with all models)

And targer:X.Y.Z-with-all-models is directly derived from targer:X.Y.Z (onyl one build step: copy the models to the image).
Users directly use targer:X.Y.Z-with-all-models (which we provide must not provide for each minot change).

**Comment by heinrichreimer** [comment]
If our intention is to store the models in the registry, I would rather build a separate volume image. That's cleaner, as the models are unlikely to change frequently. (I guess there will only be new models, old ones never change, @alexanderpanchenko?) I don't think, image tags fit here very well.

I agree with @mam10eks, that 6GB is okay for the registry. It is however very annoying when building images while developing.
A volume image could be orchestrated with either Docker compose or Kubernetes, so that would add to compatibility as well.
UHH doesn't have a Kubernetes cluster right now, has it?

Having a dedicated startup script seems like a good idea to me. We don't even need two: just stick with the second one @mam10eks suggested.
We then just check if the models folder exists, and then only enable the models that are mounted, if we only want to test few for development. Of course the backend container could print some warnings about the missing models, and we can have an endpoint for discovering available models. That way, the frontend app would be able to only show available models.

One problem remains the index which is undoubtedly too large to fit in any container.

So I'd stick with a container, without models and index.
It should have a standard entry point that downloads models (from a configurable repository) and index, if not mounted, and an offline entry point, that fails fast if models and index are not mounted.

Users deploying target could then decide, whether to supply models via mount, volume image, or URL download.

**Comment by alexanderpanchenko** [comment]
as soon as you include installation scripts for Kubernetes on a void Linux machine and make sure it works (including all other dependencies) it sounds great to me. if to make it run some very complex environment will be assumed it sounds like a not so good idea to me. the test: given a fresh Linux Ubuntu, do you have a bash script which will in less than 1 hour install everything (assuming that the ES index is downloaded)?

**Comment by alexanderpanchenko** [comment]
@mam10eks 

> Do the models change very frequently, i.e. frequent changes of the image?).

The models are static and uncompressed AFAIK, but may be stored in a format which is hard to compress. 

> If you really do not want to include the models into the image, I would suggest:

This sounds like a good plan. But we need to make sure the scripts are free of bugs and works under various conditions and tested. The question is whether the effort woth the hassle? If the system will be very actively developed in the future, probably yes, if we just want it for archival purposes maybe it makes sense just to include it as is (if somebody want to use locally the system she need to download 6+GB anyways whether it is all in one image or models separately). So the convinience only comes here for the developer, not for the user (probably for the user it is just easier to ``docker pull`` and that is it).

>One problem remains the index which is undoubtedly too large to fit in any container.

Indeed I do not see the need even to share it actually. It should be just used by all applications from Webis server which has to be available publicly. In UHH we done so with CAM http://ltdemos.informatik.uni-hamburg.de/depcc/login (login:pass for read only is reader:reader). Also we have an api..

**Comment by mam10eks** [comment]
@heinrichreimer I agree, dedicated images for models would be better than tags.

**Comment by mam10eks** [comment]
> The question is whether the effort woth the hassle?

I also think it should be fine to stick with one single 6GB image.
It will save much effort.

**Comment by alexanderpanchenko** [comment]
> One problem remains the index which is undoubtedly too large to fit in any container.

This is for sure, but the index IMO should be hosted only at Webis and shared publicly. The other parts may be deployed locally. Making the deployment of index Webis-specific is totally fine with me.

**Comment by heinrichreimer** [comment]
We decided to deploy the Docker image without models and mount a volume containing those.
